"""Schema registry for deterministic synthetic manufacturing datasets."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class DatasetSchema:
    """Metadata used by generators, manifests, validation, and tests."""

    dataset_name: str
    schema_version: str
    filename: str
    file_format: str
    primary_key: tuple[str, ...]
    fields: tuple[str, ...]
    data_types: dict[str, str]
    nullable_fields: tuple[str, ...]
    categorical_domains: dict[str, tuple[str, ...]] = field(default_factory=dict)
    timestamp_fields: tuple[str, ...] = ()
    units: dict[str, str] = field(default_factory=dict)
    relationships: dict[str, str] = field(default_factory=dict)
    invariants: tuple[str, ...] = ()
    logical_owner: str = "manufacturing_intelligence"
    synthetic_data_classification: str = "synthetic_portfolio_sample"


SCHEMA_VERSION = "1.0.0"

SCHEMAS: dict[str, DatasetSchema] = {
    "production_events": DatasetSchema(
        dataset_name="production_events",
        schema_version=SCHEMA_VERSION,
        filename="production_events.jsonl",
        file_format="jsonl",
        primary_key=("event_id",),
        fields=(
            "event_id",
            "event_timestamp",
            "plant_id",
            "production_line_id",
            "machine_id",
            "product_id",
            "production_order_id",
            "batch_id",
            "shift_id",
            "planned_quantity",
            "produced_quantity",
            "accepted_quantity",
            "rejected_quantity",
            "cycle_time_seconds",
            "target_cycle_time_seconds",
            "downtime_duration_minutes",
            "event_type",
            "operating_status",
        ),
        data_types={
            "event_id": "string",
            "event_timestamp": "timestamp",
            "plant_id": "string",
            "production_line_id": "string",
            "machine_id": "string",
            "product_id": "string",
            "production_order_id": "string",
            "batch_id": "string",
            "shift_id": "string",
            "planned_quantity": "integer",
            "produced_quantity": "integer",
            "accepted_quantity": "integer",
            "rejected_quantity": "integer",
            "cycle_time_seconds": "float",
            "target_cycle_time_seconds": "integer",
            "downtime_duration_minutes": "integer",
            "event_type": "string",
            "operating_status": "string",
        },
        nullable_fields=(),
        categorical_domains={
            "event_type": ("production_run",),
            "operating_status": ("running", "under_target", "degraded"),
        },
        timestamp_fields=("event_timestamp",),
        units={
            "cycle_time_seconds": "seconds",
            "target_cycle_time_seconds": "seconds",
            "downtime_duration_minutes": "minutes",
        },
        relationships={
            "plant_id": "catalog.plants",
            "production_line_id": "catalog.lines",
            "machine_id": "catalog.machines",
            "product_id": "catalog.products",
            "shift_id": "derived shift calendar",
        },
        invariants=("accepted_quantity + rejected_quantity = produced_quantity",),
        logical_owner="production_operations",
    ),
    "inventory_levels": DatasetSchema(
        dataset_name="inventory_levels",
        schema_version=SCHEMA_VERSION,
        filename="inventory_levels.csv",
        file_format="csv",
        primary_key=("snapshot_timestamp", "warehouse_id", "item_id"),
        fields=(
            "snapshot_timestamp",
            "warehouse_id",
            "plant_id",
            "item_id",
            "product_or_material_type",
            "on_hand_quantity",
            "reserved_quantity",
            "available_quantity",
            "reorder_point",
            "safety_stock_quantity",
            "lead_time_days",
            "unit_cost",
            "inventory_value",
            "expiry_date",
        ),
        data_types={
            "snapshot_timestamp": "timestamp",
            "warehouse_id": "string",
            "plant_id": "string",
            "item_id": "string",
            "product_or_material_type": "string",
            "on_hand_quantity": "integer",
            "reserved_quantity": "integer",
            "available_quantity": "integer",
            "reorder_point": "integer",
            "safety_stock_quantity": "integer",
            "lead_time_days": "integer",
            "unit_cost": "float",
            "inventory_value": "float",
            "expiry_date": "date",
        },
        nullable_fields=("expiry_date",),
        categorical_domains={
            "product_or_material_type": (
                "product",
                "steel",
                "aluminium",
                "electronics",
                "polymer",
                "packaging",
            )
        },
        timestamp_fields=("snapshot_timestamp",),
        units={"unit_cost": "synthetic_currency", "inventory_value": "synthetic_currency"},
        relationships={
            "warehouse_id": "catalog.warehouses",
            "plant_id": "catalog.plants",
            "item_id": "catalog.products or catalog.materials",
        },
        invariants=(
            "available_quantity = on_hand_quantity - reserved_quantity",
            "inventory_value = on_hand_quantity * unit_cost",
        ),
        logical_owner="inventory",
    ),
    "sales_orders": DatasetSchema(
        dataset_name="sales_orders",
        schema_version=SCHEMA_VERSION,
        filename="sales_orders.csv",
        file_format="csv",
        primary_key=("order_id",),
        fields=(
            "order_id",
            "order_date",
            "requested_delivery_date",
            "actual_delivery_date",
            "customer_segment",
            "product_id",
            "ordered_quantity",
            "fulfilled_quantity",
            "selling_price",
            "order_value",
            "distribution_region",
            "order_status",
        ),
        data_types={
            "order_id": "string",
            "order_date": "date",
            "requested_delivery_date": "date",
            "actual_delivery_date": "date",
            "customer_segment": "string",
            "product_id": "string",
            "ordered_quantity": "integer",
            "fulfilled_quantity": "integer",
            "selling_price": "float",
            "order_value": "float",
            "distribution_region": "string",
            "order_status": "string",
        },
        nullable_fields=(),
        categorical_domains={
            "customer_segment": (
                "automotive_oem",
                "industrial_distribution",
                "aftermarket_service",
                "export_channel",
            ),
            "distribution_region": ("north", "south", "central", "west"),
            "order_status": ("fulfilled", "partially_fulfilled", "backordered"),
        },
        timestamp_fields=("order_date", "requested_delivery_date", "actual_delivery_date"),
        units={"selling_price": "synthetic_currency", "order_value": "synthetic_currency"},
        relationships={"product_id": "catalog.products"},
        invariants=(
            "fulfilled_quantity <= ordered_quantity",
            "order_value = fulfilled_quantity * selling_price",
        ),
        logical_owner="sales_and_demand",
    ),
    "quality_checks": DatasetSchema(
        dataset_name="quality_checks",
        schema_version=SCHEMA_VERSION,
        filename="quality_checks.csv",
        file_format="csv",
        primary_key=("inspection_id",),
        fields=(
            "inspection_id",
            "inspection_timestamp",
            "plant_id",
            "line_id",
            "machine_id",
            "batch_id",
            "product_id",
            "quality_metric",
            "sample_size",
            "defective_units",
            "measured_value",
            "lower_specification_limit",
            "upper_specification_limit",
            "inspection_result",
            "defect_category",
            "severity",
        ),
        data_types={
            "inspection_id": "string",
            "inspection_timestamp": "timestamp",
            "plant_id": "string",
            "line_id": "string",
            "machine_id": "string",
            "batch_id": "string",
            "product_id": "string",
            "quality_metric": "string",
            "sample_size": "integer",
            "defective_units": "integer",
            "measured_value": "float",
            "lower_specification_limit": "float",
            "upper_specification_limit": "float",
            "inspection_result": "string",
            "defect_category": "string",
            "severity": "string",
        },
        nullable_fields=("defect_category",),
        categorical_domains={
            "quality_metric": ("diameter_mm", "surface_finish_ra", "torque_nm"),
            "inspection_result": ("pass", "fail"),
            "severity": ("none", "medium", "high"),
        },
        timestamp_fields=("inspection_timestamp",),
        units={"diameter_mm": "millimetres", "surface_finish_ra": "micrometres", "torque_nm": "nm"},
        relationships={
            "plant_id": "catalog.plants",
            "line_id": "catalog.lines",
            "machine_id": "catalog.machines",
            "batch_id": "production_events.batch_id",
            "product_id": "catalog.products",
        },
        invariants=(
            "inspection_result derives from measured_value and specification limits",
            "defective_units <= sample_size",
        ),
        logical_owner="quality",
    ),
    "equipment_health": DatasetSchema(
        dataset_name="equipment_health",
        schema_version=SCHEMA_VERSION,
        filename="equipment_health.jsonl",
        file_format="jsonl",
        primary_key=("sensor_event_id",),
        fields=(
            "sensor_event_id",
            "timestamp",
            "plant_id",
            "line_id",
            "machine_id",
            "sensor_id",
            "sensor_type",
            "measurement",
            "measurement_unit",
            "warning_threshold",
            "critical_threshold",
            "threshold_status",
            "runtime_hours",
            "service_hours_since_maintenance",
            "degradation_index",
            "operating_mode",
            "maintenance_state",
        ),
        data_types={
            "sensor_event_id": "string",
            "timestamp": "timestamp",
            "plant_id": "string",
            "line_id": "string",
            "machine_id": "string",
            "sensor_id": "string",
            "sensor_type": "string",
            "measurement": "float",
            "measurement_unit": "string",
            "warning_threshold": "float",
            "critical_threshold": "float",
            "threshold_status": "string",
            "runtime_hours": "float",
            "service_hours_since_maintenance": "float",
            "degradation_index": "float",
            "operating_mode": "string",
            "maintenance_state": "string",
        },
        nullable_fields=(),
        categorical_domains={
            "sensor_type": ("vibration", "temperature"),
            "threshold_status": ("normal", "warning", "critical"),
            "operating_mode": ("standby", "production"),
            "maintenance_state": ("normal", "warning_monitor", "critical_inspection_required"),
        },
        timestamp_fields=("timestamp",),
        units={
            "runtime_hours": "hours",
            "service_hours_since_maintenance": "hours",
            "degradation_index": "ratio",
        },
        relationships={
            "plant_id": "catalog.plants",
            "line_id": "catalog.lines",
            "machine_id": "catalog.machines",
        },
        invariants=("threshold_status derives from measurement and thresholds",),
        logical_owner="maintenance",
    ),
    "warehouse_movements": DatasetSchema(
        dataset_name="warehouse_movements",
        schema_version=SCHEMA_VERSION,
        filename="warehouse_movements.csv",
        file_format="csv",
        primary_key=("movement_id",),
        fields=(
            "movement_id",
            "movement_timestamp",
            "warehouse_id",
            "source_location",
            "destination_location",
            "item_id",
            "quantity",
            "movement_type",
            "movement_status",
            "reference_order",
            "operator_or_automated_system_id",
        ),
        data_types={
            "movement_id": "string",
            "movement_timestamp": "timestamp",
            "warehouse_id": "string",
            "source_location": "string",
            "destination_location": "string",
            "item_id": "string",
            "quantity": "integer",
            "movement_type": "string",
            "movement_status": "string",
            "reference_order": "string",
            "operator_or_automated_system_id": "string",
        },
        nullable_fields=(),
        categorical_domains={
            "movement_type": ("receipt", "issue_to_production", "transfer", "adjustment"),
            "movement_status": ("completed",),
        },
        timestamp_fields=("movement_timestamp",),
        relationships={
            "warehouse_id": "catalog.warehouses",
            "item_id": "catalog.products or catalog.materials",
            "reference_order": "synthetic source reference",
        },
        invariants=("quantity > 0",),
        logical_owner="warehouse",
    ),
    "supplier_performance": DatasetSchema(
        dataset_name="supplier_performance",
        schema_version=SCHEMA_VERSION,
        filename="supplier_performance.csv",
        file_format="csv",
        primary_key=("purchase_order_id",),
        fields=(
            "supplier_id",
            "material_id",
            "purchase_order_id",
            "order_date",
            "promised_date",
            "actual_delivery_date",
            "delay_days",
            "on_time_flag",
            "in_full_flag",
            "ordered_quantity",
            "delivered_quantity",
            "accepted_quantity",
            "rejected_quantity",
            "unit_price",
            "quality_score",
            "supplier_region",
            "delivery_status",
        ),
        data_types={
            "supplier_id": "string",
            "material_id": "string",
            "purchase_order_id": "string",
            "order_date": "date",
            "promised_date": "date",
            "actual_delivery_date": "date",
            "delay_days": "integer",
            "on_time_flag": "boolean",
            "in_full_flag": "boolean",
            "ordered_quantity": "integer",
            "delivered_quantity": "integer",
            "accepted_quantity": "integer",
            "rejected_quantity": "integer",
            "unit_price": "float",
            "quality_score": "float",
            "supplier_region": "string",
            "delivery_status": "string",
        },
        nullable_fields=(),
        categorical_domains={
            "supplier_region": ("north", "south", "central", "west"),
            "delivery_status": ("on_time_in_full", "on_time_short", "late_in_full", "late_short"),
        },
        timestamp_fields=("order_date", "promised_date", "actual_delivery_date"),
        units={"unit_price": "synthetic_currency", "quality_score": "percentage"},
        relationships={
            "supplier_id": "catalog.suppliers",
            "material_id": "catalog.materials",
        },
        invariants=(
            "accepted_quantity + rejected_quantity <= delivered_quantity",
            "delay_days = actual_delivery_date - promised_date",
            "delivery_status derives from on_time_flag and in_full_flag",
        ),
        logical_owner="supplier_performance",
    ),
}
