"""Validation rule code constants for governed ingestion."""

from __future__ import annotations

RULE_CODES = {
    "FILE_MISSING",
    "METADATA_MISSING",
    "FILE_HASH_MISMATCH",
    "FILE_SIZE_MISMATCH",
    "FILE_FORMAT_MISMATCH",
    "INVALID_UTF8",
    "INVALID_JSON",
    "INVALID_HEADER",
    "EMPTY_REQUIRED_FILE",
    "MISSING_FIELD",
    "UNKNOWN_FIELD",
    "INVALID_TYPE",
    "INVALID_CATEGORY",
    "INVALID_TIMESTAMP",
    "UNSUPPORTED_SCHEMA_VERSION",
    "DUPLICATE_PRIMARY_KEY",
    "INVALID_QUANTITY_RELATIONSHIP",
    "INVALID_DATE_RELATIONSHIP",
    "INVALID_DERIVED_FIELD",
    "INVALID_REFERENCE",
    "OUT_OF_RANGE",
    "INVALID_UNIT",
    "QUARANTINE_RATE_EXCEEDED",
}

RECOVERABLE_RECORD_RULES = {
    "MISSING_FIELD",
    "UNKNOWN_FIELD",
    "INVALID_TYPE",
    "INVALID_CATEGORY",
    "INVALID_TIMESTAMP",
    "DUPLICATE_PRIMARY_KEY",
    "INVALID_QUANTITY_RELATIONSHIP",
    "INVALID_DATE_RELATIONSHIP",
    "INVALID_DERIVED_FIELD",
    "INVALID_REFERENCE",
    "OUT_OF_RANGE",
    "INVALID_UNIT",
}

FATAL_FILE_RULES = {
    "FILE_MISSING",
    "METADATA_MISSING",
    "FILE_HASH_MISMATCH",
    "FILE_SIZE_MISMATCH",
    "FILE_FORMAT_MISMATCH",
    "INVALID_UTF8",
    "INVALID_JSON",
    "INVALID_HEADER",
    "EMPTY_REQUIRED_FILE",
    "UNSUPPORTED_SCHEMA_VERSION",
    "QUARANTINE_RATE_EXCEEDED",
}
