"""Validate the repository scaffold and generated synthetic-data assets."""

from __future__ import annotations

import sys
from pathlib import Path


def project_root() -> Path:
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "pyproject.toml").is_file():
            return parent
    raise RuntimeError("Unable to locate repository root.")


REQUIRED_PATHS = [
    ".github/workflows/ci.yml",
    "configs/platform.yaml",
    "configs/ingestion.yaml",
    "configs/ingestion_ci.yaml",
    "configs/forecasting.yaml",
    "configs/forecasting_ci.yaml",
    "configs/forecasting_extended.yaml",
    "configs/synthetic_data_forecasting.yaml",
    "configs/ingestion_forecasting.yaml",
    "configs/inventory.yaml",
    "configs/inventory_ci.yaml",
    "configs/quality.yaml",
    "configs/quality_ci.yaml",
    "configs/maintenance.yaml",
    "configs/maintenance_ci.yaml",
    "configs/monitoring.yaml",
    "configs/monitoring_ci.yaml",
    "configs/genai.yaml",
    "configs/genai_ci.yaml",
    "configs/dashboard.yaml",
    "configs/dashboard_ci.yaml",
    "configs/azure_architecture.yaml",
    "configs/azure_architecture_ci.yaml",
    "configs/synthetic_data.yaml",
    "configs/synthetic_data_ci.yaml",
    "configs/environments/local.yaml",
    "configs/environments/ci.yaml",
    "dashboard/README.md",
    "data/README.md",
    "data/raw/.gitkeep",
    "data/interim/.gitkeep",
    "data/processed/.gitkeep",
    "diagrams/high-level-platform-architecture.mmd",
    "diagrams/data-lifecycle.mmd",
    "diagrams/azure-reference-architecture.mmd",
    "diagrams/azure-data-flow.mmd",
    "diagrams/azure-security-boundary.mmd",
    "diagrams/azure-mlops-flow.mmd",
    "diagrams/azure-genai-flow.mmd",
    "diagrams/azure-monitoring-flow.mmd",
    "docs/architecture/architecture-overview.md",
    "docs/architecture/azure-service-mapping.md",
    "docs/architecture/local-first-design.md",
    "docs/architecture/azure-reference-architecture.md",
    "docs/architecture/deployment-boundary.md",
    "docs/architecture/security-architecture.md",
    "docs/architecture/data-architecture.md",
    "docs/architecture/mlops-architecture.md",
    "docs/architecture/genai-architecture.md",
    "docs/architecture/operations-architecture.md",
    "docs/architecture/cost-management.md",
    "docs/business/business-context.md",
    "docs/business/manufacturing-use-cases.md",
    "docs/business/kpi-catalogue.md",
    "docs/engineering/development-standards.md",
    "docs/engineering/data-contracts.md",
    "docs/engineering/testing-strategy.md",
    "docs/forecasting/backtesting-and-model-selection.md",
    "docs/forecasting/chronological-splitting.md",
    "docs/forecasting/demand-series-and-grain.md",
    "docs/forecasting/evaluation-metrics.md",
    "docs/forecasting/forecast-lineage-and-manifest.md",
    "docs/forecasting/forecasting-design.md",
    "docs/forecasting/leakage-prevention.md",
    "docs/forecasting/limitations.md",
    "docs/forecasting/prediction-intervals.md",
    "docs/inventory/constrained-allocation.md",
    "docs/inventory/demand-allocation.md",
    "docs/inventory/governed-inputs-and-grain.md",
    "docs/inventory/inventory-intelligence-design.md",
    "docs/inventory/inventory-lineage-and-manifest.md",
    "docs/inventory/inventory-risk-scoring.md",
    "docs/inventory/limitations.md",
    "docs/inventory/safety-stock-and-reorder-policy.md",
    "docs/inventory/scenario-analysis.md",
    "docs/quality/anomaly-detection.md",
    "docs/quality/control-charts-and-spc-rules.md",
    "docs/quality/defect-pareto-analysis.md",
    "docs/quality/governed-inputs-and-grains.md",
    "docs/quality/limitations.md",
    "docs/quality/process-capability.md",
    "docs/quality/quality-analytics-design.md",
    "docs/quality/quality-lineage-and-manifest.md",
    "docs/quality/quality-risk-scoring.md",
    "docs/quality/specification-and-yield-metrics.md",
    "docs/maintenance/predictive-maintenance-design.md",
    "docs/maintenance/governed-inputs-and-grains.md",
    "docs/maintenance/sensor-threshold-analysis.md",
    "docs/monitoring/monitoring-design.md",
    "docs/monitoring/governed-evidence-inputs.md",
    "docs/monitoring/health-scoring.md",
    "docs/monitoring/evidence-integrity-checks.md",
    "docs/monitoring/lineage-completeness.md",
    "docs/monitoring/monitoring-alerts.md",
    "docs/monitoring/observability-reports.md",
    "docs/monitoring/monitoring-lineage-and-manifest.md",
    "docs/monitoring/limitations.md",
    "docs/genai/genai-operations-assistant-design.md",
    "docs/genai/governed-evidence-catalogue.md",
    "docs/genai/retrieval-and-prompting.md",
    "docs/genai/guardrails.md",
    "docs/genai/deterministic-response-synthesis.md",
    "docs/genai/assistant-evaluation.md",
    "docs/genai/genai-lineage-and-manifest.md",
    "docs/genai/responsible-use-boundaries.md",
    "docs/genai/limitations.md",
    "docs/dashboard/dashboard-output-design.md",
    "docs/dashboard/governed-dashboard-inputs.md",
    "docs/dashboard/semantic-model.md",
    "docs/dashboard/metric-catalogue.md",
    "docs/dashboard/dashboard-pages.md",
    "docs/dashboard/visual-specifications.md",
    "docs/dashboard/dashboard-validation.md",
    "docs/dashboard/dashboard-lineage-and-manifest.md",
    "docs/dashboard/power-bi-ready-boundaries.md",
    "docs/dashboard/limitations.md",
    "docs/maintenance/degradation-analysis.md",
    "docs/maintenance/anomaly-detection.md",
    "docs/maintenance/failure-risk-scoring.md",
    "docs/maintenance/maintenance-alerts.md",
    "docs/maintenance/maintenance-lineage-and-manifest.md",
    "docs/maintenance/limitations.md",
    "docs/ingestion/data-quality-metrics.md",
    "docs/ingestion/ingestion-design.md",
    "docs/ingestion/lineage-and-manifests.md",
    "docs/ingestion/quarantine-design.md",
    "docs/ingestion/strict-vs-permissive-mode.md",
    "docs/ingestion/validation-rules.md",
    "docs/milestones/milestone-1.md",
    "docs/milestones/milestone-2.md",
    "docs/milestones/milestone-3.md",
    "docs/milestones/milestone-4.md",
    "docs/milestones/milestone-5.md",
    "docs/milestones/milestone-6.md",
    "docs/milestones/milestone-7.md",
    "docs/milestones/milestone-8.md",
    "docs/milestones/milestone-9.md",
    "docs/milestones/milestone-10.md",
    "docs/milestones/milestone-11.md",
    "docs/roadmap.md",
    "outputs/.gitkeep",
    "reports/.gitkeep",
    "reports/data_quality_report.md",
    "reports/demand_forecasting_report.md",
    "reports/inventory_intelligence_report.md",
    "reports/quality_analytics_report.md",
    "reports/quality_alert_summary.md",
    "reports/azure_architecture_report.md",
    "reports/deployment_boundary_report.md",
    "src/manufacturing_intelligence/__init__.py",
    "src/manufacturing_intelligence/common/config.py",
    "src/manufacturing_intelligence/common/exceptions.py",
    "src/manufacturing_intelligence/common/hashing.py",
    "src/manufacturing_intelligence/common/logging.py",
    "src/manufacturing_intelligence/common/paths.py",
    "src/manufacturing_intelligence/data_generation/catalog.py",
    "src/manufacturing_intelligence/data_generation/cli.py",
    "src/manufacturing_intelligence/data_generation/generator.py",
    "src/manufacturing_intelligence/data_generation/schemas.py",
    "src/manufacturing_intelligence/forecasting/__main__.py",
    "src/manufacturing_intelligence/forecasting/aggregation.py",
    "src/manufacturing_intelligence/forecasting/backtesting.py",
    "src/manufacturing_intelligence/forecasting/baselines.py",
    "src/manufacturing_intelligence/forecasting/cli.py",
    "src/manufacturing_intelligence/forecasting/config.py",
    "src/manufacturing_intelligence/forecasting/data.py",
    "src/manufacturing_intelligence/forecasting/evaluation.py",
    "src/manufacturing_intelligence/forecasting/existing_run.py",
    "src/manufacturing_intelligence/forecasting/features.py",
    "src/manufacturing_intelligence/forecasting/intervals.py",
    "src/manufacturing_intelligence/forecasting/lineage.py",
    "src/manufacturing_intelligence/forecasting/manifest.py",
    "src/manufacturing_intelligence/forecasting/models.py",
    "src/manufacturing_intelligence/forecasting/pipeline.py",
    "src/manufacturing_intelligence/forecasting/reporting.py",
    "src/manufacturing_intelligence/forecasting/selection.py",
    "src/manufacturing_intelligence/forecasting/serialization.py",
    "src/manufacturing_intelligence/forecasting/splits.py",
    "src/manufacturing_intelligence/inventory/__main__.py",
    "src/manufacturing_intelligence/inventory/cli.py",
    "src/manufacturing_intelligence/inventory/config.py",
    "src/manufacturing_intelligence/inventory/data.py",
    "src/manufacturing_intelligence/inventory/existing_run.py",
    "src/manufacturing_intelligence/inventory/lineage.py",
    "src/manufacturing_intelligence/inventory/manifest.py",
    "src/manufacturing_intelligence/inventory/pipeline.py",
    "src/manufacturing_intelligence/inventory/policy.py",
    "src/manufacturing_intelligence/inventory/reporting.py",
    "src/manufacturing_intelligence/inventory/serialization.py",
    "src/manufacturing_intelligence/quality/__main__.py",
    "src/manufacturing_intelligence/quality/anomalies.py",
    "src/manufacturing_intelligence/quality/capability.py",
    "src/manufacturing_intelligence/quality/cli.py",
    "src/manufacturing_intelligence/quality/config.py",
    "src/manufacturing_intelligence/quality/control_charts.py",
    "src/manufacturing_intelligence/quality/data.py",
    "src/manufacturing_intelligence/quality/existing_run.py",
    "src/manufacturing_intelligence/quality/lineage.py",
    "src/manufacturing_intelligence/quality/manifest.py",
    "src/manufacturing_intelligence/quality/metrics.py",
    "src/manufacturing_intelligence/quality/pareto.py",
    "src/manufacturing_intelligence/quality/pipeline.py",
    "src/manufacturing_intelligence/quality/reporting.py",
    "src/manufacturing_intelligence/quality/scoring.py",
    "src/manufacturing_intelligence/quality/serialization.py",
    "src/manufacturing_intelligence/quality/specification.py",
    "src/manufacturing_intelligence/maintenance/__main__.py",
    "src/manufacturing_intelligence/maintenance/anomalies.py",
    "src/manufacturing_intelligence/maintenance/cli.py",
    "src/manufacturing_intelligence/maintenance/config.py",
    "src/manufacturing_intelligence/maintenance/data.py",
    "src/manufacturing_intelligence/maintenance/degradation.py",
    "src/manufacturing_intelligence/maintenance/existing_run.py",
    "src/manufacturing_intelligence/maintenance/lineage.py",
    "src/manufacturing_intelligence/maintenance/manifest.py",
    "src/manufacturing_intelligence/maintenance/pipeline.py",
    "src/manufacturing_intelligence/maintenance/reporting.py",
    "src/manufacturing_intelligence/maintenance/scoring.py",
    "src/manufacturing_intelligence/maintenance/serialization.py",
    "src/manufacturing_intelligence/maintenance/summaries.py",
    "src/manufacturing_intelligence/maintenance/thresholds.py",
    "src/manufacturing_intelligence/monitoring/__main__.py",
    "src/manufacturing_intelligence/monitoring/alerts.py",
    "src/manufacturing_intelligence/monitoring/cli.py",
    "src/manufacturing_intelligence/monitoring/config.py",
    "src/manufacturing_intelligence/monitoring/data.py",
    "src/manufacturing_intelligence/monitoring/domain_checks.py",
    "src/manufacturing_intelligence/monitoring/existing_run.py",
    "src/manufacturing_intelligence/monitoring/health.py",
    "src/manufacturing_intelligence/monitoring/integrity.py",
    "src/manufacturing_intelligence/monitoring/lineage.py",
    "src/manufacturing_intelligence/monitoring/manifest.py",
    "src/manufacturing_intelligence/monitoring/pipeline.py",
    "src/manufacturing_intelligence/monitoring/reporting.py",
    "src/manufacturing_intelligence/monitoring/scoring.py",
    "src/manufacturing_intelligence/monitoring/serialization.py",
    "src/manufacturing_intelligence/monitoring/summaries.py",
    "src/manufacturing_intelligence/genai/__main__.py",
    "src/manufacturing_intelligence/genai/cli.py",
    "src/manufacturing_intelligence/genai/config.py",
    "src/manufacturing_intelligence/genai/evidence.py",
    "src/manufacturing_intelligence/genai/retrieval.py",
    "src/manufacturing_intelligence/genai/prompts.py",
    "src/manufacturing_intelligence/genai/guardrails.py",
    "src/manufacturing_intelligence/genai/synthesis.py",
    "src/manufacturing_intelligence/genai/evaluation.py",
    "src/manufacturing_intelligence/genai/examples.py",
    "src/manufacturing_intelligence/genai/pipeline.py",
    "src/manufacturing_intelligence/genai/serialization.py",
    "src/manufacturing_intelligence/genai/manifest.py",
    "src/manufacturing_intelligence/genai/lineage.py",
    "src/manufacturing_intelligence/genai/reporting.py",
    "src/manufacturing_intelligence/genai/existing_run.py",
    "src/manufacturing_intelligence/dashboard/__main__.py",
    "src/manufacturing_intelligence/dashboard/cli.py",
    "src/manufacturing_intelligence/dashboard/config.py",
    "src/manufacturing_intelligence/dashboard/data.py",
    "src/manufacturing_intelligence/dashboard/metrics.py",
    "src/manufacturing_intelligence/dashboard/semantic_model.py",
    "src/manufacturing_intelligence/dashboard/pages.py",
    "src/manufacturing_intelligence/dashboard/visuals.py",
    "src/manufacturing_intelligence/dashboard/pipeline.py",
    "src/manufacturing_intelligence/dashboard/serialization.py",
    "src/manufacturing_intelligence/dashboard/manifest.py",
    "src/manufacturing_intelligence/dashboard/lineage.py",
    "src/manufacturing_intelligence/dashboard/reporting.py",
    "src/manufacturing_intelligence/dashboard/existing_run.py",
    "src/manufacturing_intelligence/architecture/__main__.py",
    "src/manufacturing_intelligence/architecture/cli.py",
    "src/manufacturing_intelligence/architecture/config.py",
    "src/manufacturing_intelligence/architecture/artefacts.py",
    "src/manufacturing_intelligence/architecture/data.py",
    "src/manufacturing_intelligence/architecture/service_mapping.py",
    "src/manufacturing_intelligence/architecture/validation.py",
    "src/manufacturing_intelligence/architecture/manifest.py",
    "src/manufacturing_intelligence/architecture/lineage.py",
    "src/manufacturing_intelligence/architecture/reporting.py",
    "src/manufacturing_intelligence/architecture/serialization.py",
    "src/manufacturing_intelligence/architecture/pipeline.py",
    "src/manufacturing_intelligence/architecture/existing_run.py",
    "src/manufacturing_intelligence/ingestion/__main__.py",
    "src/manufacturing_intelligence/ingestion/cli.py",
    "src/manufacturing_intelligence/ingestion/config.py",
    "src/manufacturing_intelligence/ingestion/discovery.py",
    "src/manufacturing_intelligence/ingestion/existing_run.py",
    "src/manufacturing_intelligence/ingestion/loader.py",
    "src/manufacturing_intelligence/ingestion/manifest.py",
    "src/manufacturing_intelligence/ingestion/pipeline.py",
    "src/manufacturing_intelligence/ingestion/reporting.py",
    "src/manufacturing_intelligence/ingestion/serialization.py",
    "src/manufacturing_intelligence/validation/contracts.py",
    "src/manufacturing_intelligence/validation/domain_rules.py",
    "src/manufacturing_intelligence/validation/duplicates.py",
    "src/manufacturing_intelligence/validation/file_rules.py",
    "src/manufacturing_intelligence/validation/lineage.py",
    "src/manufacturing_intelligence/validation/quality.py",
    "src/manufacturing_intelligence/validation/quarantine.py",
    "src/manufacturing_intelligence/validation/record_rules.py",
    "src/manufacturing_intelligence/validation/relationships.py",
    "src/manufacturing_intelligence/validation/result.py",
    "scripts/generate_synthetic_data.py",
    "scripts/prepare_forecasting_data.py",
    "tests/unit/test_config.py",
    "tests/unit/test_repository_structure.py",
    "tests/unit/test_synthetic_data_generation.py",
    "tests/unit/test_ingestion_pipeline.py",
    "tests/unit/test_forecasting_pipeline.py",
    "tests/unit/test_inventory_pipeline.py",
    "tests/unit/test_quality_pipeline.py",
    "tests/fixtures/README.md",
    ".editorconfig",
    ".gitignore",
    ".markdownlint.json",
    ".pre-commit-config.yaml",
    "CONTRIBUTING.md",
    "LICENSE",
    "Makefile",
    "README.md",
    "pyproject.toml",
    "requirements-dev.txt",
    "infra/README.md",
    "infra/bicep/main.bicep",
    "infra/bicep/parameters.reference.json",
    "infra/bicep/modules/storage.bicep",
    "infra/bicep/modules/event-hubs.bicep",
    "infra/bicep/modules/analytics.bicep",
    "infra/bicep/modules/machine-learning.bicep",
    "infra/bicep/modules/ai-services.bicep",
    "infra/bicep/modules/monitoring.bicep",
    "infra/bicep/modules/governance.bicep",
    "infra/bicep/modules/dashboards.bicep",
    "infra/terraform/README.md",
    "infra/terraform/main.tf",
    "infra/terraform/variables.tf",
    "infra/terraform/outputs.tf",
    "infra/terraform/terraform.tfvars.example",
    "infra/policies/azure-policy-notes.md",
    "infra/policies/rbac-matrix.md",
    "infra/policies/private-networking-notes.md",
    "infra/policies/data-governance-notes.md",
    "infra/runbooks/deployment-boundary.md",
    "infra/runbooks/local-validation-runbook.md",
    "infra/runbooks/incident-response-runbook.md",
    "infra/runbooks/cost-management-runbook.md",
    "infra/runbooks/model-monitoring-runbook.md",
    "infra/runbooks/data-quality-runbook.md",
]

RAW_SYNTHETIC_OUTPUTS = [
    "data/raw/production_events.jsonl",
    "data/raw/inventory_levels.csv",
    "data/raw/sales_orders.csv",
    "data/raw/quality_checks.csv",
    "data/raw/equipment_health.jsonl",
    "data/raw/warehouse_movements.csv",
    "data/raw/supplier_performance.csv",
    "data/raw/schema_metadata.json",
    "data/raw/generation_manifest.json",
    "data/raw/generation_summary.md",
]

INTERIM_INGESTION_OUTPUTS = [
    "data/interim/accepted/production_events.jsonl",
    "data/interim/accepted/inventory_levels.csv",
    "data/interim/accepted/sales_orders.csv",
    "data/interim/accepted/quality_checks.csv",
    "data/interim/accepted/equipment_health.jsonl",
    "data/interim/accepted/warehouse_movements.csv",
    "data/interim/accepted/supplier_performance.csv",
    "data/interim/quarantine/production_events.jsonl",
    "data/interim/quarantine/inventory_levels.jsonl",
    "data/interim/quarantine/sales_orders.jsonl",
    "data/interim/quarantine/quality_checks.jsonl",
    "data/interim/quarantine/equipment_health.jsonl",
    "data/interim/quarantine/warehouse_movements.jsonl",
    "data/interim/quarantine/supplier_performance.jsonl",
    "data/interim/_metadata/ingestion-manifest.json",
    "data/interim/_metadata/validation-summary.json",
    "data/interim/_metadata/quarantine-summary.json",
    "data/interim/_metadata/data-quality-report.json",
    "data/interim/_metadata/lineage-records.json",
]

FORECAST_OUTPUTS = [
    "outputs/demand_forecast.csv",
    "outputs/forecasting/daily_demand_series.csv",
    "outputs/forecasting/feature_dataset.csv",
    "outputs/forecasting/split_metadata.json",
    "outputs/forecasting/model_comparison.csv",
    "outputs/forecasting/backtest_predictions.csv",
    "outputs/forecasting/backtest_metrics.csv",
    "outputs/forecasting/test_metrics.csv",
    "outputs/forecasting/forecast_diagnostics.json",
    "outputs/forecasting/model_metadata.json",
    "outputs/forecasting/forecast-manifest.json",
    "outputs/forecasting/lineage-records.json",
]

INVENTORY_OUTPUTS = [
    "outputs/inventory_scores.csv",
    "outputs/inventory/warehouse_demand_forecast.csv",
    "outputs/inventory/supplier_risk_metrics.csv",
    "outputs/inventory/inventory_policy_inputs.csv",
    "outputs/inventory/inventory_position.csv",
    "outputs/inventory/inventory_scores.csv",
    "outputs/inventory/inventory_health.csv",
    "outputs/inventory/reorder_recommendations.csv",
    "outputs/inventory/scenario_results.csv",
    "outputs/inventory/scenario_comparison.csv",
    "outputs/inventory/inventory_summary.json",
    "outputs/inventory/inventory_diagnostics.json",
    "outputs/inventory/inventory-manifest.json",
    "outputs/inventory/lineage-records.json",
    "reports/inventory_scenario_summary.md",
]

QUALITY_OUTPUTS = [
    "outputs/quality_alerts.csv",
    "outputs/quality/quality_observations.csv",
    "outputs/quality/quality_kpis.csv",
    "outputs/quality/defect_pareto.csv",
    "outputs/quality/process_capability.csv",
    "outputs/quality/control_chart_points.csv",
    "outputs/quality/spc_signals.csv",
    "outputs/quality/anomaly_scores.csv",
    "outputs/quality/quality_alerts.csv",
    "outputs/quality/quality_risk_summary.csv",
    "outputs/quality/quality_diagnostics.json",
    "outputs/quality/quality-manifest.json",
    "outputs/quality/lineage-records.json",
]

MAINTENANCE_OUTPUTS = [
    "outputs/maintenance_predictions.json",
    "outputs/maintenance/equipment_health_features.csv",
    "outputs/maintenance/equipment_health_scores.csv",
    "outputs/maintenance/maintenance_alerts.csv",
    "outputs/maintenance/machine_health_summary.csv",
    "outputs/maintenance/sensor_health_summary.csv",
    "outputs/maintenance/degradation_signals.csv",
    "outputs/maintenance/anomaly_scores.csv",
    "outputs/maintenance/maintenance_risk_summary.csv",
    "outputs/maintenance/maintenance_diagnostics.json",
    "outputs/maintenance/maintenance-manifest.json",
    "outputs/maintenance/lineage-records.json",
    "reports/maintenance_analytics_report.md",
    "reports/maintenance_alert_summary.md",
]

MONITORING_OUTPUTS = [
    "outputs/platform_health_summary.json",
    "outputs/monitoring/platform_health_summary.json",
    "outputs/monitoring/pipeline_health.csv",
    "outputs/monitoring/domain_health_scores.csv",
    "outputs/monitoring/data_quality_monitoring.csv",
    "outputs/monitoring/model_and_analytics_monitoring.csv",
    "outputs/monitoring/monitoring_alerts.csv",
    "outputs/monitoring/evidence_integrity_checks.csv",
    "outputs/monitoring/lineage_completeness.csv",
    "outputs/monitoring/monitoring_diagnostics.json",
    "outputs/monitoring/monitoring-manifest.json",
    "outputs/monitoring/lineage-records.json",
    "reports/platform_monitoring_report.md",
    "reports/observability_summary.md",
]

GENAI_OUTPUTS = [
    "outputs/genai/evidence_catalog.json",
    "outputs/genai/evidence_catalog.csv",
    "outputs/genai/retrieval_results.json",
    "outputs/genai/prompt_templates.json",
    "outputs/genai/rendered_prompts.json",
    "outputs/genai/assistant_responses.json",
    "outputs/genai/assistant_responses.md",
    "outputs/genai/guardrail_results.json",
    "outputs/genai/assistant_evaluation.csv",
    "outputs/genai/assistant_evaluation_summary.json",
    "outputs/genai/genai_diagnostics.json",
    "outputs/genai/genai-manifest.json",
    "outputs/genai/lineage-records.json",
    "reports/genai_operations_assistant_report.md",
    "reports/genai_guardrails_report.md",
    "reports/executive_manufacturing_brief.md",
    "reports/supply_chain_summary.md",
    "reports/manufacturing_operations_report.md",
]

DASHBOARD_OUTPUTS = [
    "outputs/dashboard/dim_date.csv",
    "outputs/dashboard/dim_product.csv",
    "outputs/dashboard/dim_plant.csv",
    "outputs/dashboard/dim_production_line.csv",
    "outputs/dashboard/dim_machine.csv",
    "outputs/dashboard/dim_warehouse.csv",
    "outputs/dashboard/dim_supplier.csv",
    "outputs/dashboard/dim_metric.csv",
    "outputs/dashboard/dim_risk_level.csv",
    "outputs/dashboard/dim_dashboard_page.csv",
    "outputs/dashboard/fact_production_kpis.csv",
    "outputs/dashboard/fact_demand_forecast.csv",
    "outputs/dashboard/fact_inventory_risk.csv",
    "outputs/dashboard/fact_quality_alerts.csv",
    "outputs/dashboard/fact_maintenance_alerts.csv",
    "outputs/dashboard/fact_platform_health.csv",
    "outputs/dashboard/fact_operations_assistant_narratives.csv",
    "outputs/dashboard/executive_scorecard.csv",
    "outputs/dashboard/metric_catalogue.csv",
    "outputs/dashboard/semantic_model.json",
    "outputs/dashboard/dashboard_page_specs.json",
    "outputs/dashboard/visual_specifications.json",
    "outputs/dashboard/dashboard_diagnostics.json",
    "outputs/dashboard/dashboard-manifest.json",
    "outputs/dashboard/lineage-records.json",
    "reports/dashboard_output_report.md",
    "reports/semantic_model_summary.md",
    "dashboard/dashboard_index.md",
    "dashboard/powerbi_ready_outputs.md",
    "dashboard/semantic_model_notes.md",
]

ARCHITECTURE_OUTPUTS = [
    "outputs/architecture/azure_service_mapping.csv",
    "outputs/architecture/azure_service_mapping.json",
    "outputs/architecture/security_controls_matrix.csv",
    "outputs/architecture/data_architecture_layers.csv",
    "outputs/architecture/mlops_mapping.csv",
    "outputs/architecture/genai_architecture_mapping.csv",
    "outputs/architecture/operations_mapping.csv",
    "outputs/architecture/cost_considerations.csv",
    "outputs/architecture/architecture_decision_records.json",
    "outputs/architecture/architecture_validation_results.json",
    "outputs/architecture/architecture-manifest.json",
    "outputs/architecture/lineage-records.json",
    "reports/azure_architecture_report.md",
    "reports/deployment_boundary_report.md",
]

PACKAGE_DIRS = [
    "common",
    "data_generation",
    "ingestion",
    "validation",
    "forecasting",
    "inventory",
    "quality",
    "maintenance",
    "monitoring",
    "genai",
    "dashboard",
    "architecture",
    "reporting",
]


def main() -> int:
    root = project_root()
    missing = [path for path in REQUIRED_PATHS if not (root / path).exists()]
    missing.extend(path for path in RAW_SYNTHETIC_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in INTERIM_INGESTION_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in FORECAST_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in INVENTORY_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in QUALITY_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in MAINTENANCE_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in MONITORING_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in GENAI_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in DASHBOARD_OUTPUTS if not (root / path).exists())
    missing.extend(path for path in ARCHITECTURE_OUTPUTS if not (root / path).exists())
    for package_dir in PACKAGE_DIRS:
        marker = root / "src" / "manufacturing_intelligence" / package_dir / "__init__.py"
        if not marker.exists():
            missing.append(str(marker.relative_to(root)))

    if missing:
        print("Repository structure check failed. Missing required paths:")
        for path in sorted(missing):
            print(f"  - {path}")
        return 1

    print("Repository structure check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
